# Generated by Django 5.2.4 on 2025-08-10 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='scripts.script')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_count', models.PositiveIntegerField(default=0)),
                ('scenes_count', models.PositiveIntegerField(default=0)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='scripts.character')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('characters', models.ManyToManyField(blank=True, related_name='scenes', to='scripts.character')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scripts.script')),
            ],
        ),
        migrations.CreateModel(
            name='SceneContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scripts.character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scripts.scene')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('contents', models.ManyToManyField(blank=True, related_name='overlays', to='scripts.scenecontent')),
            ],
        ),
    ]
